; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
build_cache_dir = $HOME/pio/cache
workspace_dir = $HOME/pio/ttgo/pio

[env:esp32dev]
;monitor_port = /dev/tty.usbserial-01E10250
;monitor_speed = 115200
platform = espressif32
board = esp32dev
build_flags = -I .
framework = arduino
lib_deps = 
	lennarthennigs/Button2@^2.0.0
	milesburton/DallasTemperature@^3.9.1
	madhephaestus/ESP32Servo@^0.11.0
	https://github.com/tzapu/WiFiManager.git
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^6.19.4
	aharshac/StringSplitter@^1.0.0
	mcxiaoke/ESPDateTime@^1.0.4
	dlloydev/QuickPID@^3.1.2
	bodmer/TFT_eSPI@^2.4.70
