// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: still2

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_times = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_times, 248);
lv_obj_set_height( ui_times, 23);
lv_obj_set_x( ui_times, 0 );
lv_obj_set_y( ui_times, -54 );
lv_obj_set_align( ui_times, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_times, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_clock = lv_label_create(ui_times);
lv_obj_set_width( ui_clock, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_clock, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_clock, 7 );
lv_obj_set_y( ui_clock, 0 );
lv_obj_set_align( ui_clock, LV_ALIGN_CENTER );
lv_label_set_text(ui_clock,"12:34:56");

ui_elapsed = lv_label_create(ui_times);
lv_obj_set_width( ui_elapsed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_elapsed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_elapsed, 7 );
lv_obj_set_y( ui_elapsed, 1 );
lv_obj_set_align( ui_elapsed, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_elapsed,"HH:MM");

ui_mqtton = lv_checkbox_create(ui_times);
lv_checkbox_set_text(ui_mqtton,"");
lv_obj_set_width( ui_mqtton, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mqtton, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_mqtton, 16 );
lv_obj_set_y( ui_mqtton, -1 );
lv_obj_set_align( ui_mqtton, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_mqtton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

lv_obj_set_style_border_side(ui_mqtton, LV_BORDER_SIDE_NONE, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_timelabel = lv_label_create(ui_times);
lv_obj_set_width( ui_timelabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_timelabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_timelabel, -45 );
lv_obj_set_y( ui_timelabel, -1 );
lv_obj_set_align( ui_timelabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_timelabel,"Time:");

ui_uplabel = lv_label_create(ui_times);
lv_obj_set_width( ui_uplabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uplabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uplabel, 51 );
lv_obj_set_y( ui_uplabel, 0 );
lv_obj_set_align( ui_uplabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_uplabel,"Up:");

ui_Label4 = lv_label_create(ui_times);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, -107 );
lv_obj_set_y( ui_Label4, 0 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Cq");

ui_temp = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_temp, 248);
lv_obj_set_height( ui_temp, 55);
lv_obj_set_x( ui_temp, 0 );
lv_obj_set_y( ui_temp, -12 );
lv_obj_set_align( ui_temp, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_temp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_treflux = lv_obj_create(ui_temp);
lv_obj_set_width( ui_treflux, 146);
lv_obj_set_height( ui_treflux, 18);
lv_obj_set_x( ui_treflux, 42 );
lv_obj_set_y( ui_treflux, -9 );
lv_obj_clear_flag( ui_treflux, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_rtemp = lv_label_create(ui_treflux);
lv_obj_set_width( ui_rtemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_rtemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_rtemp, -10 );
lv_obj_set_y( ui_rtemp, 0 );
lv_obj_set_align( ui_rtemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_rtemp,"");

ui_rdiff = lv_label_create(ui_treflux);
lv_obj_set_width( ui_rdiff, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_rdiff, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_rdiff, LV_ALIGN_CENTER );
lv_label_set_text(ui_rdiff,"+0.0");

ui_rtime = lv_label_create(ui_treflux);
lv_obj_set_width( ui_rtime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_rtime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_rtime, 8 );
lv_obj_set_y( ui_rtime, 0 );
lv_obj_set_align( ui_rtime, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_rtime,"0");

ui_tboiler = lv_obj_create(ui_temp);
lv_obj_set_width( ui_tboiler, 146);
lv_obj_set_height( ui_tboiler, 18);
lv_obj_set_x( ui_tboiler, 42 );
lv_obj_set_y( ui_tboiler, 13 );
lv_obj_clear_flag( ui_tboiler, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_btemp = lv_label_create(ui_tboiler);
lv_obj_set_width( ui_btemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_btemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_btemp, -10 );
lv_obj_set_y( ui_btemp, 0 );
lv_obj_set_align( ui_btemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_btemp,"");

ui_bdiff = lv_label_create(ui_tboiler);
lv_obj_set_width( ui_bdiff, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_bdiff, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_bdiff, LV_ALIGN_CENTER );
lv_label_set_text(ui_bdiff,"+0.0");

ui_btime = lv_label_create(ui_tboiler);
lv_obj_set_width( ui_btime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_btime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_btime, 8 );
lv_obj_set_y( ui_btime, 0 );
lv_obj_set_align( ui_btime, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_btime,"0");

ui_Label1 = lv_label_create(ui_temp);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -94 );
lv_obj_set_y( ui_Label1, -13 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Reflux");

ui_Label2 = lv_label_create(ui_temp);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -95 );
lv_obj_set_y( ui_Label2, 10 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Boiler");

ui_motorpanel = lv_obj_create(ui_temp);
lv_obj_set_width( ui_motorpanel, 39);
lv_obj_set_height( ui_motorpanel, 42);
lv_obj_set_x( ui_motorpanel, 101 );
lv_obj_set_y( ui_motorpanel, -1 );
lv_obj_set_align( ui_motorpanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_motorpanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_rspeed = lv_label_create(ui_motorpanel);
lv_obj_set_width( ui_rspeed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_rspeed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_rspeed, 0 );
lv_obj_set_y( ui_rspeed, -8 );
lv_obj_set_align( ui_rspeed, LV_ALIGN_CENTER );
lv_label_set_text(ui_rspeed,"	");

ui_pidon = lv_checkbox_create(ui_motorpanel);
lv_checkbox_set_text(ui_pidon,"");
lv_obj_set_width( ui_pidon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_pidon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_pidon, 3 );
lv_obj_set_y( ui_pidon, 9 );
lv_obj_set_align( ui_pidon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_pidon, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

lv_obj_set_style_border_side(ui_pidon, LV_BORDER_SIDE_NONE, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_messages = lv_textarea_create(ui_Screen1);
lv_obj_set_width( ui_messages, 248);
lv_obj_set_height( ui_messages, 46);
lv_obj_set_x( ui_messages, 0 );
lv_obj_set_y( ui_messages, 40 );
lv_obj_set_align( ui_messages, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_messages,1000);
lv_textarea_set_placeholder_text(ui_messages,"Messages");

}
