// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: still2

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_times;
lv_obj_t *ui_clock;
lv_obj_t *ui_elapsed;
lv_obj_t *ui_mqtton;
lv_obj_t *ui_timelabel;
lv_obj_t *ui_uplabel;
lv_obj_t *ui_Label4;
lv_obj_t *ui_temp;
lv_obj_t *ui_treflux;
lv_obj_t *ui_rtemp;
lv_obj_t *ui_rdiff;
lv_obj_t *ui_rtime;
lv_obj_t *ui_tboiler;
lv_obj_t *ui_btemp;
lv_obj_t *ui_bdiff;
lv_obj_t *ui_btime;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Label2;
lv_obj_t *ui_motorpanel;
lv_obj_t *ui_rspeed;
lv_obj_t *ui_pidon;
lv_obj_t *ui_messages;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
