// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: still2

#ifndef _STILL2_UI_H
#define _STILL2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_times;
extern lv_obj_t *ui_clock;
extern lv_obj_t *ui_elapsed;
extern lv_obj_t *ui_mqtton;
extern lv_obj_t *ui_temp;
extern lv_obj_t *ui_treflux;
extern lv_obj_t *ui_rtemp;
extern lv_obj_t *ui_rdiff;
extern lv_obj_t *ui_rtime;
extern lv_obj_t *ui_tboiler;
extern lv_obj_t *ui_btemp;
extern lv_obj_t *ui_bdiff;
extern lv_obj_t *ui_btime;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_motorpanel;
extern lv_obj_t *ui_rspeed;
extern lv_obj_t *ui_;
extern lv_obj_t *ui_messages;
extern lv_obj_t *ui____initial_actions0;

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
